
import TopBar from "@/components/TopBar";
import { Code2, Users, Zap, Target } from "lucide-react";

const About = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-pink-50 relative">
      {/* Humorous background elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-32 left-16 text-5xl opacity-10 rotate-12">🤖</div>
        <div className="absolute top-64 right-24 text-4xl opacity-10 -rotate-12">👨‍💻</div>
        <div className="absolute bottom-48 left-32 text-6xl opacity-10 rotate-45">🧠</div>
        <div className="absolute bottom-32 right-16 text-4xl opacity-10 -rotate-45">⚡</div>
      </div>

      <TopBar />
      
      <div className="max-w-4xl mx-auto px-4 py-12 relative z-10">
        <div className="text-center mb-12">
          <Code2 className="h-16 w-16 text-purple-600 mx-auto mb-6" />
          <h1 className="text-4xl font-bold text-purple-800 mb-6">
            What is "Vibe-Coded"? 🤔
          </h1>
          <p className="text-xl text-purple-600 max-w-3xl mx-auto leading-relaxed">
            In the age of AI-assisted development, we're on a mission to detect the difference between 
            code that feels like it was written by a caffeinated human at 3 AM vs. our robot friends.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 mb-12">
          <div className="bg-red-50 rounded-lg border border-red-200 p-8">
            <div className="flex items-center space-x-3 mb-4">
              <Zap className="h-6 w-6 text-red-600" />
              <h2 className="text-xl font-bold text-red-800">AI-Coded 🤖</h2>
            </div>
            <p className="text-red-700 mb-4">
              Projects that scream "I was generated by an AI that never needed coffee breaks":
            </p>
            <ul className="text-red-600 space-y-2 text-sm">
              <li>• Perfect naming conventions (too perfect, suspicious...)</li>
              <li>• Flawless TypeScript interfaces (nobody's that good)</li>
              <li>• Error handling that actually works</li>
              <li>• Comments that make sense</li>
              <li>• Zero TODO comments</li>
            </ul>
          </div>

          <div className="bg-green-50 rounded-lg border border-green-200 p-8">
            <div className="flex items-center space-x-3 mb-4">
              <Target className="h-6 w-6 text-green-600" />
              <h2 className="text-xl font-bold text-green-800">Vibe-Coded 🧑‍💻</h2>
            </div>
            <p className="text-green-700 mb-4">
              Projects with that authentic "written by a human who needs more sleep" energy:
            </p>
            <ul className="text-green-600 space-y-2 text-sm">
              <li>• Variables named "thing" and "stuff"</li>
              <li>• Creative workarounds that shouldn't work but do</li>
              <li>• Comments like "// don't ask why this works"</li>
              <li>• At least 3 TODO comments from 2019</li>
              <li>• Functions that do way more than they should</li>
            </ul>
          </div>
        </div>

        <div className="bg-yellow-50 rounded-lg border border-yellow-200 p-8 mb-12">
          <div className="flex items-center space-x-3 mb-4">
            <Users className="h-6 w-6 text-yellow-600" />
            <h2 className="text-xl font-bold text-yellow-800">How It Works 🎯</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6 text-sm">
            <div>
              <h3 className="text-yellow-800 font-medium mb-2">1. Submit</h3>
              <p className="text-yellow-700">
                Share your GitHub repo and let the internet judge your coding soul.
              </p>
            </div>
            <div>
              <h3 className="text-yellow-800 font-medium mb-2">2. Analyze</h3>
              <p className="text-yellow-700">
                Our AI detective examines your code while humans vote on the vibes.
              </p>
            </div>
            <div>
              <h3 className="text-yellow-800 font-medium mb-2">3. Discover</h3>
              <p className="text-yellow-700">
                Find out if you code like a human or if you've been replaced by AI already.
              </p>
            </div>
          </div>
        </div>

        <div className="text-center">
          <h2 className="text-2xl font-bold text-purple-800 mb-4">Join the Investigation 🕵️</h2>
          <p className="text-purple-600 mb-6">
            Help us solve the greatest mystery of our time: Who (or what) is writing all this code?
          </p>
          <div className="flex justify-center space-x-4">
            <a 
              href="/submit" 
              className="bg-blue-200 hover:bg-blue-300 text-blue-800 px-6 py-3 rounded-lg font-medium transition-colors border border-blue-300"
            >
              Submit Your Code 🚀
            </a>
            <a 
              href="/" 
              className="bg-purple-200 hover:bg-purple-300 text-purple-800 px-6 py-3 rounded-lg font-medium transition-colors border border-purple-300"
            >
              Explore Projects 🔍
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
